const UPDATE_ITEMS = 'UPDATE_ITEMS'
const ADD_ITEM = 'ADD_ITEM'
const DELETE_ITEM = 'DELETE_ITEM'
const ADD_CUSTOMER = 'ADD_CUSTOMER'
const DELETE_CUSTOMER = 'DELETE_CUSTOMER'
const MODIFY_CUSTOMER = 'MODIFY_CUSTOMER'

export {
  UPDATE_ITEMS,
  ADD_ITEM,
  DELETE_ITEM,
  ADD_CUSTOMER,
  DELETE_CUSTOMER,
  MODIFY_CUSTOMER
}